### ISSUE TITLE
Error on maker when using on APP_ENV=PROD

### ISSUE THREAD

**Issue by chanondb** [k3ssen/SymfonyVuetified#16]
Hi, I like your concept, so trying to do some test run but stuck on production due to maker bundle. 
with APP_ENV=PROD
any idea on how to solve?

`Uncaught Symfony\Component\DependencyInjection\Exception\RuntimeException: Invalid service "K3ssen\SymfonyVuetified\Maker\Generator": class "Symfony\Bundle\MakerBundle\Generator" not found while loading "K3ssen\SymfonyVuetified\Maker\Generator"`

**Comment by k3ssen** [comment]
thnx for letting me know. I shall add a fix soon (upcoming weekend probably).

For now, as a temporary workaround, you could overwrite the service. For example, you could add the file ` config/packages/prod/services.yaml`  (if you don't have this file already) and use something like:
``` 
services:
    K3ssen\SymfonyVuetified\Maker\Generator: null
 ``` 

This should ' empty'  this Generator service in the prod environment.

**Comment by chanondb** [comment]
Okie, thx

**Comment by k3ssen** [comment]
I've made a change to resolve this issue and tagged it in v0.2.4
